#!/usr/bin/env python3

import argparse
import os

parser = argparse.ArgumentParser(description='Given an elf binary and the name of a symbol, output the (virtual) address of that symbol')
parser.add_argument('path_to_binary')
parser.add_argument('symbol_name')

args = parser.parse_args()

os.system(f'avr-nm {args.path_to_binary} | grep {args.symbol_name}')
