name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: simavr
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y gcc make gcc-avr avr-libc libelf-dev freeglut3 freeglut3-dev libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev pkg-config libncurses-dev git cpputest 
    - name: Install Collections-C Library Dependency
      run: cd .. && git clone https://github.com/srdja/Collections-C.git && cd Collections-C && mkdir build && cd build && cmake .. && make && make test && sudo make install && sudo ldconfig
    - name: Build
      run: make all
    - name: Test
      run: make -C tests run_tests

